/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ercMapleSol from "./ERCMaple.sol";
export type { ercMapleSol };
import type * as ercOpenZeppelinSol from "./ERCOpenZeppelin.sol";
export type { ercOpenZeppelinSol };
import type * as ercSoladySol from "./ERCSolady.sol";
export type { ercSoladySol };
import type * as ercSolmateSol from "./ERCSolmate.sol";
export type { ercSolmateSol };
import type * as mockErcMapleSol from "./MockERCMaple.sol";
export type { mockErcMapleSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
