/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ercOpenZeppelinSol from "./ERCOpenZeppelin.sol";
export type { ercOpenZeppelinSol };
import type * as ercSoladySol from "./ERCSolady.sol";
export type { ercSoladySol };
import type * as ercSoladyMockSol from "./ERCSoladyMock.sol";
export type { ercSoladyMockSol };
