/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyToken2__factory } from "./MyToken2__factory";
export { OpenZeppelin__factory } from "./OpenZeppelin__factory";
